### ISSUE TITLE
Production Mode Icons go Missing

### ISSUE THREAD

**Issue by zeknox** [TikiTDO/trumbowyg_rails#2]
Just wondering if you have ever run into this where the icons work great in development mode, but once you change rails over to production mode the icons will go blank like shown below.

Looked through the JS console but didn't see anything. Perhaps I need to add an additional directory for asset compilation?

![editor](https://cloud.githubusercontent.com/assets/2473269/7893351/83eea402-0622-11e5-86e5-3a31709ef7a5.png)

**Comment by TikiTDO** [comment]
Looks good, thanks. I've pushed the changes to gem version 1.1.3
