### ISSUE TITLE
Editor won't start due to problem with svgPath

### ISSUE THREAD

**Issue by AndKiel** [TikiTDO/trumbowyg_rails#6]
When trying to initialize trumbowyg like that:
`$ ->
  $('.trumbowyg').trumbowyg()`

I get:

> TypeError: stackLines[Number(...)].match(...) is null
> http://192.168.13.37/assets/trumbowyg/trumbowyg.self-2531006bb68a51ccd07d714f86693312eb36f552384a75ef975d560d207ae5aa.js?body=1
> Line 166

When I provide any svgPath, for example:
`$ ->
  $('.trumbowyg').trumbowyg(svgPath: false)`
it's working (but no icons, just empty buttons).

For now a quick solution for me was putting trumbowyg icons SVG file in public/images and providing path as svgPath parameter.

**Comment by TikiTDO** [comment]
This is a combination of two problems. One is a bug with how the original library parses URLs, the other is an issue with how rails creates asset digests. I submitted a pull request for the first in the original repo. I'll see if I can come up with something for the second.

**Comment by snvl1993** [comment]
@AndKiel, try to set svgPath as below:

``` javascript
$('.trumbowyg').trumbowyg(svgPath: '/assets/trumbowyg/images/icons.svg')
```

it works for me.

**Comment by AndKiel** [comment]
@snvl1993, it works in development but in production I get 404.

**Comment by TikiTDO** [comment]
@AndKiel As long as you are running this code within an erb context you could do something like this:

``` javascript
$('.trumbowyg').trumbowyg(svgPath: '<%= image_path "/images/icons.svg" %>')
```

It's not very neat but it should get the job done. Once I have some more time I'm going to come back to this and write some sort of migration script that makes the required adjustments automatically on release, but I have no idea when I'll have enough time to do that.
